'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''DropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnDeleteList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCreateNewList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNewList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtNewListName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewListName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar1 As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblTotalExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalExpenses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dataGridViewExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataGridViewExpenses As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblTotalRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''remainingChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents remainingChart As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''lblListName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''expensesChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents expensesChart As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''lblhousingCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhousingCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHousingExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHousingExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHousingRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHousingRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFoodCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFoodCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFoodExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFoodExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFoodRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFoodRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUtilitiesCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtilitiesCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUtilitiesExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtilitiesExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUtilitiesRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtilitiesRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntertainmentCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntertainmentCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntertainmentExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntertainmentExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntertainmentRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntertainmentRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClothingCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClothingCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClothingExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClothingExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClothingRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClothingRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCarCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCarExpensePermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarExpensePermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCarRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDebtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebtCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDebtPermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebtPermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDebtRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebtRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSavingsCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSavingsCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSavingsPermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSavingsPermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSavingsRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSavingsRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMiscellaneousCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiscellaneousCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMiscellaneousPermited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiscellaneousPermited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMiscellaneousRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiscellaneousRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMonthlyTake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthlyTake As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHousingPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHousingPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFoodPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFoodPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUtilitiesPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUtilitiesPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCarPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDebtPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDebtPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSavingsPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSavingsPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClothingPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClothingPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEntertainmentPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntertainmentPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMiscellaneousPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiscellaneousPercent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEditConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditConfiguration As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSaveConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveConfiguration As Global.System.Web.UI.WebControls.Button
End Class
